---
- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - workflow-aggregator
    - credentials-binding
    - docker-workflow
    - pipeline
    - pipeline-stage-view
    - ssh-agent
    - nodejs
    - maven-plugin
    - gradle

- name: Ensure Jenkins is started
  service:
    name: jenkins
    state: started
    enabled: yes
